version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8003:8003"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
  
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
